# Generated by Django 5.1.4 on 2024-12-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='land',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
