# Generated by Django 5.1.4 on 2025-01-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0002_land_length_land_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Length must be in meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='In Tsh', max_digits=12),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.DecimalField(decimal_places=2, help_text='Size must be in cm²', max_digits=10),
        ),
        migrations.AlterField(
            model_name='land',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Width must be in meters', max_digits=10),
        ),
    ]
